name: playkosmos_activity
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/svg/activity_posters/
    - assets/flyer_placeholder/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
    - family: PassionOne
      fonts:
        - asset: fonts/PassionOne-Regular.ttf
        - asset: fonts/PassionOne-Bold.ttf
    - family: Bevan
      fonts:
        - asset: fonts/Bevan-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: fonts/Lalezar-Regular.ttf
    - family: BlackHanSans
      fonts:
        - asset: fonts/BlackHanSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Medium.ttf
        - asset: fonts/Oswald-SemiBold.ttf
        - asset: fonts/Oswald-Bold.ttf
    - family: OleoScript
      fonts:
        - asset: fonts/OleoScript-Bold.ttf
    - family: Teko
      fonts:
        - asset: fonts/Teko-Bold.ttf
        - asset: fonts/Teko-Medium.ttf
        - asset: fonts/Teko-SemiBold.ttf
    - family: PTSansNarrow
      fonts:
        - asset: fonts/PTSansNarrow-Bold.ttf
    - family: Akshar
      fonts:
        - asset: fonts/Akshar-Bold.ttf
        - asset: fonts/Akshar-Medium.ttf
        - asset: fonts/Akshar-SemiBold.ttf
    - family: SquadaOne
      fonts:
        - asset: fonts/SquadaOne-Regular.ttf
    - family: BlackOpsOne
      fonts:
        - asset: fonts/BlackOpsOne-Regular.ttf
    - family: Play
      fonts:
        - asset: fonts/Play-Bold.ttf
        - asset: fonts/Play-Regular.ttf
    - family: SairaStencilOne
      fonts:
        - asset: fonts/SairaStencilOne-Regular.ttf
    - family: Cabin
      fonts:
        - asset: fonts/Cabin-Bold.ttf
        - asset: fonts/Cabin-Medium.ttf
        - asset: fonts/Cabin-Regular.ttf
        - asset: fonts/Cabin-SemiBold.ttf
    - family: Bangers
      fonts:
        - asset: fonts/Bangers-Regular.ttf
    - family: Calistoga
      fonts:
        - asset: fonts/Calistoga-Regular.ttf
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Bold.ttf
        - asset: fonts/Rajdhani-SemiBold.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-BoldItalic.ttf
    - family: SuezOne
      fonts:
        - asset: fonts/SuezOne-Regular.ttf
    - family: Chivo
      fonts:
        - asset: fonts/Chivo-Regular.ttf
    - family: BigshotOne
      fonts:
        - asset: fonts/BigshotOne-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Bold.ttf
        # Added newly
        - asset: fonts/SourceSansPro-Black.ttf
    - family: Archivo
      fonts:
        - asset: fonts/Archivo-Bold.ttf
        - asset: fonts/Archivo-Black.ttf
        - asset: fonts/Archivo-ExtraBold.ttf
        - asset: fonts/Archivo-Medium.ttf
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-SemiBold.ttf
        - asset: fonts/IBMPlexSans-Bold.ttf
    # Added newly
    - family: IBMPlexSansCondensed
      fonts:
        - asset: fonts/IBMPlexSansCondensed-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Black.ttf
        - asset: fonts/Raleway-SemiBold.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-Medium.ttf
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Black.ttf
        - asset: fonts/Lexend-Bold.ttf
    - family: AnekKannada
      fonts:
        - asset: fonts/AnekKannada-ExtraBold.ttf
        - asset: fonts/AnekKannada-Bold.ttf
    - family: YanoneKaffeesatz
      fonts:
        - asset: fonts/YanoneKaffeesatz-Bold.ttf
    - family: AbrilFatface
      fonts:
        - asset: fonts/AbrilFatface-Regular.ttf
    - family: AbrilFatface
      fonts:
        - asset: fonts/SecularOne-Regular.ttf
    - family: Ubuntu-Medium.tff
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: Jost-Black.tff
      fonts:
        - asset: fonts/Jost-Black.ttf
    - family: Karla-ExtraBold.tff
      fonts:
        - asset: fonts/Karla-ExtraBold.ttf
    - family: GemunuLibre-ExtraBold.tff
      fonts:
        - asset: fonts/GemunuLibre-ExtraBold.ttf
    - family: TradeWinds-Regular.tff
      fonts:
        - asset: fonts/TradeWinds-Regular.ttf
    - family: DoppioOne-Regular.tff
      fonts:
        - asset: fonts/DoppioOne-Regular.ttf
    - family: BigShouldersText-Black.tff
      fonts:
        - asset: fonts/BigShouldersText-Black.ttf
    - family: RadioCanada-Bold.tff
      fonts:
        - asset: fonts/RadioCanada-Bold.ttf
    - family: Manuale-ExtraBold.tff
      fonts:
        - asset: fonts/Manuale-ExtraBold.ttf
    - family: kanit-BlackItalic.tff
      fonts:
        - asset: fonts/kanit-BlackItalic.ttf
    - family: kanit-Medium.tff
      fonts:
        - asset: fonts/kanit-Medium.ttf
    - family: kanit-Bold.tff
      fonts:
        - asset: fonts/kanit-Bold.ttf
    - family: AlumniSans-Bold.tff
      fonts:
        - asset: fonts/AlumniSans-Bold.ttf
    - family: AlumniSans-ExtraBold.tff
      fonts:
        - asset: fonts/AlumniSans-ExtraBold.ttf
    - family: Katibeh-Regular.tff
      fonts:
        - asset: fonts/Katibeh-Regular.ttf
    - family: GermaniaOne-Regular.tff
      fonts:
        - asset: fonts/GermaniaOne-Regular.ttf
    - family: NotoSans-Black.tff
      fonts:
        - asset: fonts/NotoSans-Black.ttf
    - family: Lobster-Regular.tff
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Bayon-Regular.tff
      fonts:
        - asset: fonts/Bayon-Regular.ttf
    - family: Glory-ExtraBold.tff
      fonts:
        - asset: fonts/Glory-ExtraBold.ttf
    - family: Heebo-Bold.tff
      fonts:
        - asset: fonts/Heebo-Bold.ttf
    - family: Tapestry-Regular.tff
      fonts:
        - asset: fonts/Tapestry-Regular.ttf
    - family: Unbounded-Bold.tff
      fonts:
        - asset: fonts/Unbounded-Bold.ttf
    - family: Unbounded-ExtraBold.tff
      fonts:
        - asset: fonts/Unbounded-ExtraBold.ttf
    - family: TitilliumWeb-Black.tff
      fonts:
        - asset: fonts/TitilliumWeb-Black.ttf
    - family: Barlow-Black.tff
      fonts:
        - asset: fonts/Barlow-Black.ttf
    - family: Dosis-ExtraBold.tff
      fonts:
        - asset: fonts/Dosis-ExtraBold.ttf
    - family: Assistant-Bold.tff
      fonts:
        - asset: fonts/Assistant-Bold.ttf
    - family: Hind-Bold.tff
      fonts:
        - asset: fonts/Hind-Bold.ttf
    - family: FasterOne-Regular.tff
      fonts:
        - asset: fonts/FasterOne-regular.ttf
    - family: Poppins-ExtraBold.tff
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf
    - family: Poppins-Black.tff
      fonts:
        - asset: fonts/Poppins-Black.ttf
    - family: Neuton-ExtraBold.tff
      fonts:
        - asset: fonts/Neuton-ExtraBold.ttf
    - family: SairaCondensed-Black.tff
      fonts:
        - asset: fonts/SairaCondensed-Black.ttf
    - family: TitilliumWeb-Bold.tff
      fonts:
        - asset: fonts/TitilliumWeb-Bold.ttf
    - family: TitanOne-Regular.tff
      fonts:
        - asset: fonts/TitanOne-Regular.ttf
    - family: Tomorrow-ExtraBold.tff
      fonts:
        - asset: fonts/Tomorrow-ExtraBold.ttf
    - family: Tomorrow-Bold.tff
      fonts:
        - asset: fonts/Tomorrow-Bold.ttf
    - family: Kanit-ExtraBold.tff
      fonts:
        - asset: fonts/Kanit-ExtraBold.ttf
    - family: ArchivoBlack-Regular.tff
      fonts:
        - asset: fonts/ArchivoBlack-Regular.ttf
    - family: Manrope-ExtraBold.tff
      fonts:
        - asset: fonts/Manrope-ExtraBold.ttf
    - family: SofiaSans-Black.tff
      fonts:
       - asset: fonts/SofiaSans-Black.ttf
    - family: Dosis-Bold.tff
      fonts:
        - asset: fonts/Dosis-Bold.ttf
    - family: Rowdies-Regular.tff
      fonts:
        - asset: fonts/Rowdies-Regular.ttf
    - family: Rowdies-Bold.tff
      fonts:
        - asset: fonts/Rowdies-Bold.ttf
    - family: Coda-ExtraBold.tff
      fonts:
        - asset: fonts/Coda-ExtraBold.ttf
    - family: Coda-Regular.tff
      fonts:
        - asset: fonts/Coda-Regular.ttf
    - family: Quantico-Bold.tff
      fonts:
        - asset: fonts/Quantico-Bold.ttf
    - family: BowlbyOne-Regular.tff
      fonts:
        - asset: fonts/BowlbyOne-Regular.ttf
    - family: BowlbyOneSC-Regular.tff
      fonts:
        - asset: fonts/BowlbyOneSC-Regular.ttf
    - family: LilitaOne-Regular.tff
      fonts:
       - asset: fonts/LilitaOne-Regular.ttf
    - family: Shrikhand-Regular.tff
      fonts:
        - asset: fonts/Shrikhand-Regular.ttf
    - family: PermanentMarker-Regular.tff
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: Rye-Regular.tff
      fonts:
        - asset: fonts/Rye-Regular.ttf
    - family: Tomorrow-Medium.tff
      fonts:
        - asset: fonts/Tomorrow-Medium.ttf
    - family: RacingSansOne-Regular.tff
      fonts:
        - asset: fonts/RacingSansOne-Regular.ttf
    - family: Coiny-Regular.tff
      fonts:
        - asset: fonts/Coiny-Regular.ttf
    - family: BubblegumSans-Regular.tff
      fonts:
        - asset: fonts/BubblegumSans-Regular.ttf



    




